<a href="https://colab.research.google.com/github/Samhitha140/ML-23AG1A66D1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

NumPy is a Python library created in 2005 that performs numerical calculations. It is generally used for working with arrays.

NumPy also includes a wide range of mathematical functions, such as linear algebra, Fourier transforms, and random number generation, which can be applied to arrays.

**Why Use Numpy**

In Python, we use lists to work with arrays. But when it comes to large array operations, Python lists are not optimized enough.

Numpy arrays are optimized for complex mathematical and statistical operations. Operations on NumPy are up to 50x faster than iterating over native Python lists using loops.

In [1]:

import numpy as np


NumPy Array Creation

In [2]:
l1=[2,3,4,5,6]
arr1=np.array(l1)
print(arr1)

[2 3 4 5 6]


In [3]:
arr1=np.array([2,3,4,5,6])
print(arr1)

[2 3 4 5 6]


In [4]:
arr1=np.array([[2,3,4,5],
               [4,9,8,7]])

print(arr1)

[[2 3 4 5]
 [4 9 8 7]]


In [6]:
arr1=np.array([[[2,3,4,5],
               [4,9,8,7],
                [3,6,7,8]],

              [[3,7,8,9],
               [7,0,9,8],
               [7,9,8,6]]])

print(arr1)

[[[2 3 4 5]
  [4 9 8 7]
  [3 6 7 8]]

 [[3 7 8 9]
  [7 0 9 8]
  [7 9 8 6]]]


In [7]:
arr1 = np.array([2, 4, 6])

# check the data type of array1
print(arr1.dtype)


int64


Check dimensions of an Numpy Array

In [8]:
print(arr1.ndim)

1


Check Size of Numpy array

In [9]:

print(arr1.size)

3


**NumPy Array shape Attribute**

In NumPy, the shape attribute returns a tuple of integers that gives the size of the array in each dimension.

In [10]:
arr1 = np.array([[1, 2, 3],
                [6, 7, 8]])

# return a tuple that gives size of array in each dimension
print(arr1.shape)

(2, 3)


**NumPy Array itemsize Attribute**

In NumPy, the itemsize attribute determines size (in bytes) of each element in the array.

In [16]:
# create a default 1-D array of integers
arr1 = np.array([6, 7, 8, 10, 13])

# create a 1-D array of 32-bit integers
arr2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)

# use of itemsize to determine size of each array element of array1 and array2
print(arr1.itemsize)
print(arr2.itemsize)


8
4


**NumPy Array data Attribute**

In NumPy, we can get a buffer containing actual elements of the array in memory using the data attribute.

In simpler terms, the data attribute is like a pointer to the memory location where the array's data is stored in the computer's memory.

In [13]:
arr1 = np.array([6, 7, 8])
arr2 = np.array([[1, 2, 3],
                   	    [6, 7, 8]])

# print memory address of array1's and array2's data
print("Data of array1 is: ",arr1.data)
print("Data of array2 is: ",arr2.data)


Data of array1 is:  <memory at 0x7ac9338d3400>
Data of array2 is:  <memory at 0x7ac9335a0110>


Access Array Elements Using Index

In [18]:
arr1[1]=10
print(arr1)


[ 6 10  8 10 13]


2-D NumPy Array Indexing

In [19]:
# create a 2D array
array1 = np.array([[1, 3, 5, 7],
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])


# access the element at the second row and fourth column
element1 = array1[1, 3]  # returns 15
print("4th Element at 2nd Row:",element1)

# access the element at the first row and second column
element2 = array1[0, 1]  # returns 3
print("2nd Element at First Row:",element2)

4th Element at 2nd Row: 15
2nd Element at First Row: 3


**NumPy Statistical Functions**

Functions

median() return the median of an array

mean() return the mean of an array

std() return the standard deviation of an array

percentile() return the nth percentile of elements in an array

min() return the minimum element of an array

max() return the maximum element of an array

In [20]:
# create a 1D array with 5 elements
array1 = np.array([1, 2, 3, 4, 5])

# calculate the median
median = np.median(array1)

print(median)

3.0


Compute Mean Using NumPy

In [21]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the mean of marks
mean_marks = np.mean(marks)

print(mean_marks)



77.2


Standard Deviation of NumPy Array

In [22]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.std(marks)
print(std_marks)


6.368673331236263


Numpy Percentile

In [24]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.percentile(marks,50)
print(std_marks)


78.0


Numpy min

In [23]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.min(marks)
print(std_marks)

66


Numpy max

In [25]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.max(marks)
print(std_marks)



85
